language: generic
sudo: required

services:
    - docker
before_install:
    - docker build -t ankurbnsl8099/docker_react -f Dockerfile.dev .
script:
    - docker run -e CI=true ankurbnsl8099/docker_react npm run test